AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RdsSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group attached to the RDS instance

  Ec2SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id 
    Description: Security group attached to the EC2 instance

Resources:
  RdsIngressFromEc2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RdsSecurityGroupId
      IpProtocol: tcp
      FromPort: 1433 
      ToPort: 1433
      SourceSecurityGroupId: !Ref Ec2SecurityGroupId